### ISSUE TITLE
Kaniko can't use cache towards Dockerhub unless the repo is defined as well

### ISSUE THREAD

**Issue by alegri90** [evry-ace/jenkins-ace-library#29]
https://github.com/evry-ace/jenkins-ace-library/blob/e5be291f3bf6e8c8bb377079d122905384e97f61/vars/kanikoBuild.groovy#L19

See issue: https://github.com/GoogleContainerTools/kaniko/issues/524

So either drop `--cache=true` or force it to also include `--cache-repo=<something>/cache` when used.

**Comment by alegri90** [comment]
@ekarlso -- This is the current reason Kaniko won't build right now.

**Comment by alegri90** [comment]
And please remove the last `,`, as it is not proper syntax 😉

**Comment by ekarlso** [comment]
Fixed in latest commits.
